---
- set_fact: check_hostname="{{ ansible_host }}"

- name: detect username and ssh-availability
  local_action: shell "{{ role_path }}/scripts/wait-for-ssh" --timeout 300 --check-cloud-user --print-user "{{ check_hostname }}"
  register: remote_user_name

- name: install python (needed by ansible, pfew..)
  # TODO: non-fedora distros (patches welcome)
  raw: test -f /usr/bin/dnf && dnf -y install /usr/bin/python

- name: allow root ssh connections
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^disable_root:'
    line: 'disable_root: 0'
  remote_user: "{{ remote_user_name.stdout_lines[0] }}"
  become: true
  become_user: root

- name: use the same authorized_keys
  replace:
    path: /root/.ssh/authorized_keys
    regexp: '.*Please login as the user.* ssh-rsa '
    replace: 'ssh-rsa '
    backup: yes
  remote_user: "{{ remote_user_name.stdout_lines[0] }}"
  become: true
  become_user: root
